#ifndef __ADD_SCENESELECTOR_H__
#define __ADD_SCENESELECTOR_H__

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include "add_common.h"

/*********************************************************************
 * MACROS
 */
#if defined(SCENE_SELECTOR)
#define ADD_SCENESELECTOR_KEY_SCENE1 P0_4
#define ADD_SCENESELECTOR_KEY_SCENE2 P0_5
#define ADD_SCENESELECTOR_KEY_SCENE3 P0_0
#define ADD_SCENESELECTOR_KEY_SCENE4 P2_0
#define ADD_SCENESELECTOR_KEY_DIMMINGUP P1_6
#define ADD_SCENESELECTOR_KEY_DIMMINGDOWN P1_7

#elif defined(SCENE_SELECTOR_TOUCHKEY)
#define ADD_SCENESELECTOR_APT8L08_TP_INT P2_0
#define ADD_SCENESELECTOR_APT8L08_SDA  P0_4
#define ADD_SCENESELECTOR_APT8L08_SCL P0_5

#else
#endif

/*********************************************************************
 * CONSTANTS
 */
// OSAL NV item IDs
#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT1_SCENEID 0x0501 // 2byte
#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT2_SCENEID 0x0503 // 2byte
#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT3_SCENEID 0x0505 // 2byte
#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT4_SCENEID 0x0507 // 2byte

#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT1_GROUPID 0x0581 // 2byte
#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT2_GROUPID 0x0583 // 2byte
#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT3_GROUPID 0x0585 // 2byte
#define ADD_SCENESELECTOR_NV_ITEM_ID_ENDPOINT4_GROUPID 0x0587 // 2byte

#if defined(SCENE_SELECTOR)
#elif defined(SCENE_SELECTOR_TOUCHKEY)

#define ADD_SCENESELECTOR_APT8L08_POWERON_DELAY 50 // 50ms

#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_SYSCON 0x3a
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_MCON 0x21
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_BUR 0x22
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_DMR0 0x2d
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_DMR1 0x2a
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KDR0 0x23
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_GSR 0x20
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR00 0x00
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR01 0x01
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR02 0x02
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR03 0x03
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR04 0x04
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR05 0x05
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR06 0x06
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR07 0x07
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR08 0x08
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR09 0x09
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR0A 0x0a
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR0B 0x0b
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR0C 0x0c
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR0D 0x0d
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR0E 0x0e
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KOR0F 0x0f
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_SYSCON 0x3a
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KVR0 0x34
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KVR1 0x35

#define ADD_SCENESELECTOR_APT8L08_MODE_NORMAL 0x00
#define ADD_SCENESELECTOR_APT8L08_MODE_CONFIGURE 0x5a

#define ADD_SCENESELECTOR_OUTPUT 1
#define ADD_SCENESELECTOR_INPUT 0
#define ADD_SCENESELECTOR_APT8L08_SDA_DIR(dir) if (dir) {P0DIR |= 0x10;} else {P0DIR &= ~0x10;}
#define ADD_SCENESELECTOR_APT8L08_SCL_DIR(dir) if (dir) {P0DIR |= 0x20;} else {P0DIR &= ~0x20;}

#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_GSR 0x04 //0X04 //全局灵敏度 4mm 亚克力 0x01
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_MCON 0x54 //0X04 //mcon 当使用AT8L08时,高4位一定要配置为“5";当使用AT8L16时,高4位配置为“0”;BIT2:"1"表示多键,"0"单键；BIT3:"1"表示与上次按键不一样产生INT约0.7ms,"0"有按键一直低,无按键拉高。
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_FILTER0 0x00
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K0_ENB 0x03 //K07~K00(BIT7:BIT0)置”1“ 禁止TK0x功能
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K1_ENB 0xff //0x00 //K17~K10(BIT7:BIT0)置”1“ 禁止TK1x功能
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_SENSE_CON 0x00
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_SENSE_S 0x08
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_GSR_K07 0x02
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_GSR_K17 0x02
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_REF_UTH 0x10
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_KEY_ATH 0x10
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_DSMIT 0x04
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_MCONH 0x40
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_FILTER1 0x00
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K0_CON 0x00
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K1_CON 0x00
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K0_OUT 0xff
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K1_OUT 0xff
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K0_IN 0xff
#define ADD_SCENESELECTOR_APT8L08_REGISTER_DATA_K1_IN 0xff

#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_GSR 0x20
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_MCON 0x21
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_FILTER0 0x22
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K0_ENB 0x23
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K1_ENB 0x24
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_SENSE_CON 0x25
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_SENSE_S 0x26
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_GSR_K07 0x27
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_GSR_K17 0x28
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_REF_UTH 0x29
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_KEY_ATH 0x2a
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_DSMIT 0x2b
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_MCONH 0x2c
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_FILTER1 0x2d
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K0_CON 0x18
#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K1_CON 0x19
//#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K0_OUT 0x1b
//#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K1_OUT 0x1a
//#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K0_IN 0x1c
//#define ADD_SCENESELECTOR_APT8L08_REGISTER_ADDRESS_K1_IN 0x1d

#define ADD_SCENESELECTOR_APT8L08_TK_TK_NUM 8

#define ADD_SCENESELECTOR_APT8L08_TOUCHKEY_SCENE1 0x0004
#define ADD_SCENESELECTOR_APT8L08_TOUCHKEY_SCENE2 0x0020
#define ADD_SCENESELECTOR_APT8L08_TOUCHKEY_SCENE3 0x0008
#define ADD_SCENESELECTOR_APT8L08_TOUCHKEY_SCENE4 0x0040
#define ADD_SCENESELECTOR_APT8L08_TOUCHKEY_DIMMINGUP 0x0010
#define ADD_SCENESELECTOR_APT8L08_TOUCHKEY_DIMMINGDOWN 0x0080

#else
#endif

#define ADD_SCENESELECTOR_FACTORYRESET_KEYNORMAL 0x00
#define ADD_SCENESELECTOR_FACTORYRESET_KEYDOWN_5S 0x01
#define ADD_SCENESELECTOR_FACTORYRESET_KEYDOWN_10S 0x02

#define ADD_SCENESELECTOR_WAKEUP_KEYNORMAL 0x00
#define ADD_SCENESELECTOR_WAKEUP_KEYDOWN_5S 0x01
#define ADD_SCENESELECTOR_WAKEUP_KEYDOWN_10S 0x02

/*********************************************************************
 * VARIABLES
 */

/*********************************************************************
 * FUNCTIONS
 */
extern void addSceneSelector_init(void);
extern uint16 addSceneSelector_eventLoop(uint8 task_id, uint16 events);
extern void addSceneSelector_isrPort0(void);
extern void addSceneSelector_isrPort1(void);
extern void addSceneSelector_isrPort2(void);

extern void addSceneSelector_sendLevelControlMove(void);
extern void addSceneSelector_factoryResetCheck(void);
extern void addSceneSelector_wakeupCheck(void);
extern void addSceneSelector_setGroupID(uint8 endPoint, aps_Group_t *group);
extern void addSceneSelector_setSceneID(uint8 endPoint, zclGeneral_Scene_t *scene);

#ifdef __cplusplus
}
#endif

#endif /* __ADD_SCENESELECTOR_H__ */

